"""Shared neutral identities for governance tests; never imported by production."""
ENTERPRISE = "InternalEnterprise"
HEALTHCARE_CLIENT_ALPHA = "ClientAlpha"
HEALTHCARE_CLIENT_BETA = "ClientBeta"
KNOWN_NON_HEALTHCARE_CLIENT = "ClientEpsilon"
UNCLASSIFIED_CLIENT = "ClientUnclassified"
BUSINESS_CENTER_01 = "BusinessCenter01"
BUSINESS_CENTER_02 = "BusinessCenter02"
BUSINESS_CENTER_2014 = "2014"
BUSINESS_CENTER_2270 = "2270"
PROJECT_ALPHA = "ProjectAlpha"
PROJECT_BETA = "ProjectBeta"
ENTERPRISE_COLLECTION = "Enterprise Standards"
