"""Explainable file-classification heuristics.

Every classification comes with a short human-readable reason string so the
inventory never silently asserts something it can't justify. Nothing here
infers architectural importance from filename or size alone.
"""
from __future__ import annotations

from pathlib import Path

DOC_EXTENSIONS = {".md", ".rst", ".adoc"}
CONFIG_EXTENSIONS = {".yml", ".yaml", ".toml", ".ini", ".cfg", ".conf"}
SCHEMA_HINT_NAMES = ("schema",)
SHELL_EXT = {".sh": "script_shell", ".bash": "script_shell",
             ".ps1": "script_powershell", ".psm1": "script_powershell",
             ".bat": "script_batch", ".cmd": "script_batch"}
BUILD_FILENAMES = {
    "setup.py", "setup.cfg", "pyproject.toml", "makefile", "dockerfile",
    "manifest.in", "requirements.txt", "package.json", "package-lock.json",
    "poetry.lock", "pipfile", "pipfile.lock",
}
GENERATED_MARKERS = (
    "do not edit", "auto-generated", "autogenerated", "@generated",
    "generated by", "this file is generated",
)
GENERATED_PATH_HINTS = ("_pb2.py", "_pb2_grpc.py", "/migrations/", ".g.cs", ".designer.cs")
VENDOR_PATH_HINTS = ("/vendor/", "/third_party/", "/thirdparty/", "/site-packages/")


def is_test_path(rel_posix: str, filename: str) -> bool:
    lower = rel_posix.lower()
    lname = filename.lower()
    if "/tests/" in f"/{lower}" or lower.startswith("tests/") or lower.startswith("test/"):
        return True
    if lname.startswith("test_") or lname.endswith("_test.py") or lname.endswith("_tests.py"):
        return True
    if lname == "conftest.py":
        return True
    return False


def classify_file(rel_posix: str, filename: str, ext: str, sample_text: str | None) -> tuple[str, str]:
    """Return (category, reason). sample_text is a small text prefix, or None for binary."""
    lname = filename.lower()

    if lname in BUILD_FILENAMES or lname.startswith("requirements") and ext == ".txt":
        return "build_packaging", f"recognized build/packaging filename '{filename}'"

    if ext == ".py":
        if is_test_path(rel_posix, filename):
            return "test", "path or filename matches test conventions (tests/ dir, test_*.py, conftest.py)"
        return "python_source", "'.py' extension"

    if ext in DOC_EXTENSIONS or lname in ("readme", "license", "changelog"):
        return "documentation", f"'{ext or filename}' is a documentation extension/filename"

    if ext == ".json":
        if "schema" in lname:
            return "json_schema", "filename contains 'schema'"
        if sample_text and '"$schema"' in sample_text:
            return "json_schema", "file contains a top-level \"$schema\" key"
        if lname in ("package.json", "package-lock.json", "tsconfig.json", ".eslintrc.json"):
            return "configuration", f"recognized configuration filename '{filename}'"
        return "data", "'.json' extension without schema markers"

    if ext in CONFIG_EXTENSIONS or lname.startswith(".env"):
        return "configuration", f"'{ext or filename}' is a configuration extension/filename"

    if ext in SHELL_EXT:
        return SHELL_EXT[ext], f"'{ext}' script extension"

    if ext in (".csv", ".tsv", ".xml"):
        return "data", f"'{ext}' data extension"

    if ext == ".txt":
        return "documentation" if lname == "readme.txt" else "data", "'.txt' extension"

    if ext == ".py":  # unreachable, kept for clarity
        return "python_source", "'.py' extension"

    return "unsupported_text", f"no classification rule matched extension '{ext}'"


def detect_generated_or_vendor(rel_posix: str, sample_text: str | None) -> str:
    lower = f"/{rel_posix.lower()}"
    for hint in GENERATED_PATH_HINTS:
        if hint in lower:
            return "generated"
    for hint in VENDOR_PATH_HINTS:
        if hint in lower:
            return "vendor"
    if sample_text:
        head = sample_text[:2000].lower()
        for marker in GENERATED_MARKERS:
            if marker in head:
                return "generated"
    return "no"


def detect_entrypoint_reason(rel_posix: str, has_main_guard: bool) -> str | None:
    lname = Path(rel_posix).name.lower()
    if has_main_guard:
        return "contains `if __name__ == \"__main__\":` guard"
    if lname in ("manage.py", "app.py", "main.py", "cli.py", "__main__.py"):
        return f"conventional entrypoint filename '{lname}'"
    return None


# --- Operational-role classification (routing catalogs) ---------------
#
# Conservative and evidence-based: every result comes with the rule that
# produced it. An uncertain case is never silently reported as "active" --
# it falls through to "unknown" instead. Only Python files are classified
# (operational role depends on __main__-guard/docstring evidence that only
# exists for parsed Python source).

ARCHIVED_PATH_HINTS = ("/_archive/", "/archive/", "/legacy/", "/deprecated/")
MIGRATION_PATH_HINTS = ("/migration/", "/migrations/")
OPERATOR_TOP_DIRS = {"runner", "scripts", "bin", "dev_tools"}
OPERATOR_FILENAMES = {"main.py", "cli.py", "manage.py", "app.py", "__main__.py"}
OPERATOR_DOCSTRING_HINTS = ("entry point", "entrypoint", "command-line", "command line", "usage:")
UTILITY_TOP_DIRS = {"tools", "dev_tools"}

OPERATIONAL_ROLES = (
    "operator_entrypoint", "active_pipeline", "developer_utility",
    "test_harness", "migration", "archived_or_legacy", "library_module", "unknown",
)


def classify_operational_role(rel_posix: str, filename: str, category: str, ext: str,
                               has_main_guard: bool, docstring_first_line: str | None,
                               generated_or_vendor: str) -> tuple[str, str]:
    """Return (role, evidence). `role` is always one of OPERATIONAL_ROLES."""
    lower_path = f"/{rel_posix.lower()}"
    lname = filename.lower()

    if category == "test":
        return "test_harness", "file classified as 'test' (test-path/filename convention, see classify_file)"

    for hint in ARCHIVED_PATH_HINTS:
        if hint in lower_path:
            return "archived_or_legacy", f"path contains archival directory segment '{hint.strip('/')}'"

    for hint in MIGRATION_PATH_HINTS:
        if hint in lower_path:
            return "migration", f"path contains migration directory segment '{hint.strip('/')}'"
    if lname.startswith("migrate_"):
        return "migration", "filename starts with 'migrate_'"

    if generated_or_vendor != "no":
        return "unknown", f"file marked '{generated_or_vendor}' by generated/vendor heuristics; operational role not inferred for generated/vendor files"

    if ext != ".py":
        return "unknown", "operational-role classification only supports Python files (needs __main__-guard/docstring evidence)"

    top_dir = rel_posix.split("/")[0] if "/" in rel_posix else ""
    docstring_lower = (docstring_first_line or "").lower()

    if has_main_guard or lname in OPERATOR_FILENAMES:
        evidence_bits = []
        if has_main_guard:
            evidence_bits.append("contains `if __name__ == \"__main__\":` guard")
        if lname in OPERATOR_FILENAMES:
            evidence_bits.append(f"conventional entrypoint filename '{lname}'")
        if top_dir in OPERATOR_TOP_DIRS:
            return "operator_entrypoint", "; ".join(evidence_bits) + f"; located under operator-facing directory '{top_dir}/'"
        for hint in OPERATOR_DOCSTRING_HINTS:
            if hint in docstring_lower:
                return "operator_entrypoint", "; ".join(evidence_bits) + f"; module docstring mentions '{hint}'"
        return "active_pipeline", ("; ".join(evidence_bits)
                                    + "; no operator-facing directory or docstring hint matched, "
                                      "conservatively treated as an active pipeline stage rather than an operator entrypoint")

    if category == "python_source":
        if top_dir in UTILITY_TOP_DIRS:
            return "developer_utility", f"no `__main__` guard; located under developer-tooling directory '{top_dir}/'"
        return "library_module", (
            f"no `__main__` guard; located under '{top_dir}/'" if top_dir
            else "no `__main__` guard; module at repository root"
        )

    return "unknown", "no operational-role rule matched"
