"""Explainable file-classification heuristics.

Every classification comes with a short human-readable reason string so the
inventory never silently asserts something it can't justify. Nothing here
infers architectural importance from filename or size alone.
"""
from __future__ import annotations

from pathlib import Path

DOC_EXTENSIONS = {".md", ".rst", ".adoc"}
CONFIG_EXTENSIONS = {".yml", ".yaml", ".toml", ".ini", ".cfg", ".conf"}
SCHEMA_HINT_NAMES = ("schema",)
SHELL_EXT = {".sh": "script_shell", ".bash": "script_shell",
             ".ps1": "script_powershell", ".psm1": "script_powershell",
             ".bat": "script_batch", ".cmd": "script_batch"}
BUILD_FILENAMES = {
    "setup.py", "setup.cfg", "pyproject.toml", "makefile", "dockerfile",
    "manifest.in", "requirements.txt", "package.json", "package-lock.json",
    "poetry.lock", "pipfile", "pipfile.lock",
}
GENERATED_MARKERS = (
    "do not edit", "auto-generated", "autogenerated", "@generated",
    "generated by", "this file is generated",
)
GENERATED_PATH_HINTS = ("_pb2.py", "_pb2_grpc.py", "/migrations/", ".g.cs", ".designer.cs")
VENDOR_PATH_HINTS = ("/vendor/", "/third_party/", "/thirdparty/", "/site-packages/")


def is_test_path(rel_posix: str, filename: str) -> bool:
    lower = rel_posix.lower()
    lname = filename.lower()
    if "/tests/" in f"/{lower}" or lower.startswith("tests/") or lower.startswith("test/"):
        return True
    if lname.startswith("test_") or lname.endswith("_test.py") or lname.endswith("_tests.py"):
        return True
    if lname == "conftest.py":
        return True
    return False


def classify_file(rel_posix: str, filename: str, ext: str, sample_text: str | None) -> tuple[str, str]:
    """Return (category, reason). sample_text is a small text prefix, or None for binary."""
    lname = filename.lower()

    if lname in BUILD_FILENAMES or lname.startswith("requirements") and ext == ".txt":
        return "build_packaging", f"recognized build/packaging filename '{filename}'"

    if ext == ".py":
        if is_test_path(rel_posix, filename):
            return "test", "path or filename matches test conventions (tests/ dir, test_*.py, conftest.py)"
        return "python_source", "'.py' extension"

    if ext in DOC_EXTENSIONS or lname in ("readme", "license", "changelog"):
        return "documentation", f"'{ext or filename}' is a documentation extension/filename"

    if ext == ".json":
        if "schema" in lname:
            return "json_schema", "filename contains 'schema'"
        if sample_text and '"$schema"' in sample_text:
            return "json_schema", "file contains a top-level \"$schema\" key"
        if lname in ("package.json", "package-lock.json", "tsconfig.json", ".eslintrc.json"):
            return "configuration", f"recognized configuration filename '{filename}'"
        return "data", "'.json' extension without schema markers"

    if ext in CONFIG_EXTENSIONS or lname.startswith(".env"):
        return "configuration", f"'{ext or filename}' is a configuration extension/filename"

    if ext in SHELL_EXT:
        return SHELL_EXT[ext], f"'{ext}' script extension"

    if ext in (".csv", ".tsv", ".xml"):
        return "data", f"'{ext}' data extension"

    if ext == ".txt":
        return "documentation" if lname == "readme.txt" else "data", "'.txt' extension"

    if ext == ".py":  # unreachable, kept for clarity
        return "python_source", "'.py' extension"

    return "unsupported_text", f"no classification rule matched extension '{ext}'"


def detect_generated_or_vendor(rel_posix: str, sample_text: str | None) -> str:
    lower = f"/{rel_posix.lower()}"
    for hint in GENERATED_PATH_HINTS:
        if hint in lower:
            return "generated"
    for hint in VENDOR_PATH_HINTS:
        if hint in lower:
            return "vendor"
    if sample_text:
        head = sample_text[:2000].lower()
        for marker in GENERATED_MARKERS:
            if marker in head:
                return "generated"
    return "no"


def detect_entrypoint_reason(rel_posix: str, has_main_guard: bool) -> str | None:
    lname = Path(rel_posix).name.lower()
    if has_main_guard:
        return "contains `if __name__ == \"__main__\":` guard"
    if lname in ("manage.py", "app.py", "main.py", "cli.py", "__main__.py"):
        return f"conventional entrypoint filename '{lname}'"
    return None
